import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-auto-dealer-warranty-reimbursement-recovery",
  "engine": "recovery",
  "title": "Auto Dealer Warranty Reimbursement Recovery",
  "shortTitle": "Dealer Warranty Recovery",
  "tagline": "Recover OEM warranty labor, parts, diagnostic, and campaign reimbursement",
  "industry": "Automotive Dealer Fixed Operations",
  "uiPort": 4559,
  "apiPort": 5559,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "OEM warranty claims paid at supported labor, parts, and operation values",
  "valueNarrative": "Connect repair orders, labor operations, technician time, parts, OEM policies, warranty submissions, and remittances.",
  "calculation": {
    "actualKey": "reimbursedAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "OEM reimbursed amount",
    "expectedLabel": "Dealer-supported amount",
    "varianceLabel": "Potential warranty recovery",
    "direction": "expected-minus-actual",
    "finding": "Repair-order, labor, parts, and OEM policy evidence indicate warranty reimbursement shortfall.",
    "actions": [
      "Validate VIN, coverage, causal part, and repair narrative",
      "Recalculate labor operations and parts reimbursement",
      "Correct or appeal the OEM claim",
      "Reconcile remittance and technician or parts accounting"
    ]
  }
},[
feature("oem-policy-and-rate-library","DWR01","OEM policy and rate library","Reconcile oem policy and rate library using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed oem policy and rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("vin-and-warranty-eligibility","DWR02","VIN and warranty eligibility","Reconcile vin and warranty eligibility using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed vin and warranty eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("repair-order-ingestion","DWR03","Repair-order ingestion","Reconcile repair-order ingestion using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed repair-order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("labor-operation-validation","DWR04","Labor operation validation","Reconcile labor operation validation using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed labor operation validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("technician-time-reconciliation","DWR05","Technician time reconciliation","Reconcile technician time reconciliation using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed technician time reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("parts-reimbursement-calculation","DWR06","Parts reimbursement calculation","Reconcile parts reimbursement calculation using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed parts reimbursement calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("diagnostic-time-recovery","DWR07","Diagnostic-time recovery","Reconcile diagnostic-time recovery using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed diagnostic-time recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("sublet-and-towing-recovery","DWR08","Sublet and towing recovery","Reconcile sublet and towing recovery using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed sublet and towing recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("recall-and-campaign-claims","DWR09","Recall and campaign claims","Reconcile recall and campaign claims using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed recall and campaign claims decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("claim-edit-and-documentation-control","DWR10","Claim edit and documentation control","Reconcile claim edit and documentation control using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed claim edit and documentation control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("rejected-claim-classification","DWR11","Rejected claim classification","Reconcile rejected claim classification using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed rejected claim classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("oem-appeal-package","DWR12","OEM appeal package","Reconcile oem appeal package using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed oem appeal package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("claim-response-and-resubmission","DWR13","Claim response and resubmission","Reconcile claim response and resubmission using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed claim response and resubmission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("remittance-reconciliation","DWR14","Remittance reconciliation","Reconcile remittance reconciliation using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed remittance reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]}),
feature("dealer-recovery-analytics","DWR15","Dealer recovery analytics","Reconcile dealer recovery analytics using repair orders, VIN warranty status, labor operations, technician time, parts costs, OEM policies, claim status, and remittances.","Produce a governed dealer recovery analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["manufacturer","Manufacturer","text","Northstar Motors"],["repairOrder","Repair Order / VIN","text","RO-884120 / VIN-4K18"],["reimbursedAmount","OEM Reimbursed Amount","currency",284000],["eligibleAmount","Dealer Eligible Amount","currency",347500]],{amountField:"reimbursedAmount",subjects:["Powertrain warranty repair","Recall campaign repair","EV battery claim","Goodwill repair","Diagnostic-time appeal"]})
]);
